---
server:
  port: 8080

spring:
  liquibase:
    enabled: true
  datasource:
#    url: jdbc:postgresql://0.0.0.0:5432/task-tracker
#    url: jdbc:postgresql://pg15/postgres
    url: jdbc:postgresql://greenplum.lab.karpov.courses:6432/karpovcourses
    username: student
    password: Wrhy96_09iPcreqAS
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    show-sql: true